### ISSUE TITLE
Incoming Feature : Support multi-root-workspaces

### ISSUE THREAD

**Issue by glennsarti** [lingua-pupuli/puppet-vscode#119]
VS Code will soon be supporting multi-root-workspace feature on extensions.  Need to figure out if we need to do anything about it.

https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs

**Comment by jpogran** [comment]
Observations from attempting to use workspaces with the Puppet extension.

Steps:

- Open VSCode
- Open folder, choose `folder1` with 1 or more Puppet files.
- Open Puppet file.
- File - Add folder to workspace - Choose `folder2` with 1 or more Puppet files
- Open Puppet file in `folder2`

Observed:

- Puppet extension is loaded when a Puppet file in `folder1` is opened. LanguageServer workspace commandline is give `folder1` as path. All features appear to work.
- Adding the new folder to workspace is effectively a reload, and causes the extension to be reloaded. It still receives `folder1` as the workspace. Extension loads fine. All features appear to work when using a file in `folder1`. 
- Choosing a file in `folder2` does not produce any errors. Syntax highlighting and grammar appear to work. Hover support works, but looks like it still is 'looking' at `folder1`.

**Comment by glennsarti** [comment]
Yeah...probably time to address this.

**Comment by AlexisLessard** [comment]
While hovering over ressourcees didn't seem to show anything for me, it eventually started working. Not sure what happened, but autocomplete and hover documentation works correctly for me. I'm on windows 10 using pdk 6.0.2.

**Comment by jpogran** [comment]
@AlexisLessard did you mean to reply to this issue? This issue is about implementing a new feature, not about any problems with autocomplete or hover support. If you are having problems with those, can you open a new issue?

**Comment by AlexisLessard** [comment]
@jpogran More or less, I had an issue with it, but it works fine, with a bit of patience with the pdk. And I'm using a multi root workspace in vscode 1.28.2. So this is more to say that multi-root workspaces support already works for me.
