### ISSUE TITLE
Use the PDK ruby instance if the native puppet-agent does not exist

### ISSUE THREAD

**Issue by glennsarti** [lingua-pupuli/puppet-vscode#130]
Some people are unable to install a native puppet-agent, but are able to instead install the PDK.  The PDK does include a native ruby environment as well as puppet gem and its required gems.  This means the VS Code language server will be able to take advantage of this.

This ticket is to add detection of a PDK setup and use that ruby environment if a native agent is not available.  As this is a cross platform tools, this detection should also be cross platform

**Comment by glennsarti** [comment]
Removing from 0.7 milestone as the prep is done but not enabled yet for 0.7

**Comment by glennsarti** [comment]
@jpogran This can probably be closed now?

**Comment by jpogran** [comment]
@glennsarti Yep
