### ISSUE TITLE
Feature - Start the Language Server as a docker container

### ISSUE THREAD

**Issue by glennsarti** [lingua-pupuli/puppet-vscode#212]
Feature Request - Instead of always running the Language Server in the same OS as the VS Code client, perhaps we could call docker to start a container and either use STDIO or TCP to communicate with it.

Solves:
- Fixes issue #171 
- Allows users to easily run Linux (and Windows containers) on Mac OSX and Windows (Using LCOW)

Problems:
- Do we use an image with Puppet prebaked? If not, how do get it on there?
- Do we publish a Language Server container on Docker Hub? (Various Linux variants + Windows) (Least preferred)

**Comment by glennsarti** [comment]
There are a bunch of containers at https://hub.docker.com/u/puppet/

**Comment by glennsarti** [comment]
Example

Where `C:\Source\tmp\puppet-vscode\server` is the absolute path to the language server code.

docker run -i --tty --rm -v "C:\Source\tmp\puppet-vscode\server:/project" -p 8083:8083 --entrypoint "ruby" puppet/puppet-agent-alpine /project/puppet-languageserver --debug=STDOUT --ip=0.0.0.0 --port=8083 --timeout=30

**Comment by jpogran** [comment]
Step 1 - define docker template(?) for use
Step 2 - add as startup option for extension

**Comment by jpogran** [comment]
So this has been largely been replaced by #375, so closing this
