### ISSUE TITLE
Switch from Puppet to PDK requirement

### ISSUE THREAD

**Issue by jpogran** [lingua-pupuli/puppet-vscode#215]
Moving from requiring a Puppet agent install to a PDK install would be beneficial because:

- [x] Less burden on user to install
- [x] More likely to have PDK installed on dev workstation instead of Puppet agent
- [x] Potential integration points into the PDK instead of copy pasting commands to console 

This would require:

- [x] Investigate list of features PDK supports and determine if we can solely use PDK instead of Puppet
- [x] Abstract ruby and Puppet runtime detection to allow us to switch to PDK
- [x] Find integration points into the PDK

**Comment by dhollinger** [comment]
@jpogran has there been any movement on this recently?

**Comment by jpogran** [comment]
@dhollinger yes there has, but it wasn't specifically tracked here in this ticket. I'll fix that now


Not all of the below was worked on in the order it apears, this is just a logical grouping of the changelog (we know we need to update it to follow more closely to keep-a-changelog).

We first had to split the repo into a client and server repo as part of our org move. This allowed us to streamline deployment and focus on features in the right places. 

- #250 Move client folder to root
- #253 Remove languageserver
- #252 Update readme for org move
- #258 Vendoring process for editor services
- #275 Update Marketplace Categories
- (maint) Update github links for org change
- (maint) Automatically download languageserver on build and watch
- (maint) Improve issue templates

If we were to allow choosing PDK or Puppet Agent, we had to change alot of code in many different places that was duplicated. This wasn't optimal, and would be fragile. We targeted cleaning up the codebase and updating some syntax and grammar parts

- (maint) Fix tslint errors
- (maint) Update Puppet grammer file
- Update Puppet Editor Services to 0.12.0
- #284 Add support for region folding
- #296 Set document file scheme
- #289 Fix autoindenting for DSL

Standardizing the detection of puppet and ruby and the connection configuration was our next step. We made STIOD the default connection method, fixed some open TCP bugs, and fixed some spagethi code for determined paths. This took alot of time, but put us in a better place to make the PDK changes.

- (maint) Refactor client connection code
- #238 Add stdio support to client extension
- #241 Honor specified tcp port
- #240 Add TCP retry functionality
- #274 Remove random tcp port resolution from client

Since by this time it had been awhile since last release, we decided to fixup a couple small issues and then work on PDK next release.

- #301 Fail fast if agent not installed
- #310 Fix gulp bump
- #307 Fix path resolution on mac and *nix

I have been spiking what the code will look like to handle PDK for the past couple days, but haven't put the tickets in yet. As you may know, the paths for Puppet Agent and PDK are different, as well as each installer has different paths in each OS. We want to support you choosing either, so we have to do some work to 'find' all the parts we need with all those variables in the mix. You should see the progress for this in the https://github.com/orgs/lingua-pupuli/projects/1 project

**Comment by glennsarti** [comment]
@jpogran To log a separate issue on the PDK starting handler not raising an error on older PDK versions (e.g. 1.2) which have different paths.

**Comment by jpogran** [comment]
https://github.com/lingua-pupuli/puppet-vscode/issues/338 and https://github.com/lingua-pupuli/puppet-vscode/issues/339 are created

**Comment by jpogran** [comment]
@dhollinger I you are interested, there is a development build of the Puppet VSCode Extension here: https://ci.appveyor.com/api/buildjobs/8ylgt5403keuwqu4/artifacts/puppet-vscode-99.99.0-appv.15.vsix. This allows the extension to use the PDK instead of a Puppet Agent for source, and introduces two new configuration options. By default the `puppet.installType` is set to `pdk`, and allows you to choose to use `pdk` or `puppet-agent`. The `puppet.installDirectory` allows you to choose a custom path to either a PDK install or a Puppet-Agent install, and must match the correct setting in `puppet.installType`. If no settings are chosen, the extension will attempt to use the PDK, to force it to use Puppet-Agent you have to select `puppet` for `puppet.installType`.

*Note*: Only PDK v1.5.0 and above are supported. Prior to v1.5.0, the PDK did not include the puppet gem and we could not use it.

In order to use this build, you must first uninstall the current released version (0.11.0), then install from vsix this build. When done testing, uninstall this build and go to the gallery to install the current released version. Any feedback or issues, please use the github page.

**Comment by KosherSalt** [comment]
Feedback for the test build:
Installed easily, no errors that I saw. 
I'm using PDK v1.6.0 and Windows 10. I also tested on Fedora with PDK v1.6.1

* Node graph
  * Did not work. 
    *  Windows - There were no resources created in the node graph. Is there an include statement missing?
     * Fedora - Same message but also received message about language server not ready.
* intellisense
    Worked for both. Started typing package and it provided the snippet. Then started to type provider and it correctly suggested.
* definition peek - was unable to figure out how to do this
* go to definition - was unable to figure out how to do this
* puppet resource command from pallette
   - worked on Windows. Put the data into the current file.
   - did not work on fedora. Got message about language server not ready. Tried restarting code, but still failed.

**Comment by michaeltlombardi** [comment]
@KosherSalt: Can you share the manifest you used to test with re: Node Graph, definition peek?

**Comment by KosherSalt** [comment]
For the Linux side I was trying with the puppetboard module. On windows i used an internal module so I can’t share it.

**Comment by jpogran** [comment]
#338 and #339 opened to track the final elements from this epic ticket

**Comment by jpogran** [comment]
@KosherSalt I'm going to close this issue as it's more of an epic ticket than an individual issue ticket. We released the 0.11.1 today, can you check to see if things work over there and open a new issue if things still don't work for you?
