### ISSUE TITLE
Support parsing plans

### ISSUE THREAD

**Issue by MikaelSmith** [lingua-pupuli/puppet-vscode#224]
When parsing Puppet plans, puppet requires the `--tasks` flag (or `Puppet[:tasks]`) set to true.

Currently this extension errors on plans. Presumably that could be fixed by setting the `tasks` setting to true when evaluating files in a `plans` directory of a module.

As an example
```
plan foo::pattern(
  Pattern[/^[^\/\\]*$/] $p = 'hello'
) {
  notice($p)
}
```
results in the error `Could not parse for environment *root*: Syntax error at 'p' (line: 2, column: 25)`.

Using macOS 10.13, Puppet 5.4.0, VSCode 1.20.1.

**Comment by glennsarti** [comment]
Thanks @MikaelSmith .  Looks like an easy fix

**Comment by jpogran** [comment]
So, this doesn't look as easy as a fix as we thought. In PR #233 first pass is implemented, but it blows up trying to compile the catalog: https://travis-ci.org/jpogran/puppet-vscode/jobs/353409249

**Comment by MikaelSmith** [comment]
Yeah, the `tasks` flag can't be enabled for everything, it's essentially a different parser when enabled. Maybe it could be made to work, but I think some changes are enabled that aren't compatible with the original Puppet language.

**Comment by ripienaar** [comment]
yes, several features are disabled and defaults tweaked if you enable --tasks, this should somehow only be on for stuff in the `plans` subdirectory

**Comment by jpogran** [comment]
We load Puppet once, so would have to think more about this

**Comment by glennsarti** [comment]
Closing and now tracking in https://github.com/lingua-pupuli/puppet-editor-services/issues/24
