### ISSUE TITLE
Feature Request: add custom path for puppet modules, support parameter autocomplete

### ISSUE THREAD

**Issue by Betriebsrat** [lingua-pupuli/puppet-vscode#225]
Currently we have quite a few modules developed on our own. It would be nice if you could add a custom module path to the language server where it reads all modules and sets the autocomplete up correctly.

Could be that there is already such a feature as:

> ./puppet-languageserver --help 

gives me

> --local-workspace=PATH       The workspace or file path that will be used to provide module-specific functionality. Default is no workspace path.

but i got no clue how to use that within vscode itself (theres no such option).

**Comment by glennsarti** [comment]
Hi @Betriebsrat .  The VSCode client is supposed to handle supplying that option for you transparently.  It was added in https://github.com/jpogran/puppet-vscode/pull/111/files but...somehow it's gone missing.  Need to investigate that...

As for adding additional module search paths, this comes directly from puppet. So you will need to add that to the modulepath.

https://puppet.com/docs/puppet/5.2/dirs_modulepath.html

**Comment by glennsarti** [comment]
Looks like that code was removed on the next commit - https://github.com/jpogran/puppet-vscode/commit/45bd0203dde24e595a26cdfbaf32ec91ac30ddb7#diff-f8c56798d343acc77582c0a5f4f8ed62

**Comment by Betriebsrat** [comment]
another question..., how would i switch to bleeding edge version on vscode?

**Comment by glennsarti** [comment]
Do you mean bleeding edge of this extension?

**Comment by Betriebsrat** [comment]
yes sorry this extension

**Comment by glennsarti** [comment]
Ok.  VS Code can install extensions from a VSIX file.  You can see in the Pull Requests on Appveyor we build this so you can try out new builds straight away.

We don't release "bleeding" edge but you can get it from;
1. Browse to;
https://ci.appveyor.com/project/jpogran/puppet-vscode

2. Open the last test cell `Environment: nodejs_version=7.4.0, nodejs_arch=x64, VSCE_TASK=package`

3. Click on the `Artifacts` tab and there you'll find the latest build

**Comment by Betriebsrat** [comment]
thanks alot!

**Comment by glennsarti** [comment]
yeah.... :-)  Something else to fix :-)

**Comment by glennsarti** [comment]
Further to add.

Autocomplete doesn't take into account defines or puppet classes, only custom types.  Need to update that.

**Comment by jpogran** [comment]
@glennsarti Is the last comment a new ticket? Or something that was address in commit https://github.com/lingua-pupuli/puppet-vscode/commit/12e4d27552ac60a2aaa80890d5c9b7d4cddbb125

**Comment by glennsarti** [comment]
@jpogran That last comment is a feature request for the editor-services.

However the original question is adding a non-default module path.  This will require a feature update to editor services (not too hard, just need to inject the folders into the modulepath at runtime) and a configuration option in the extension.

**Comment by glennsarti** [comment]
Raised https://github.com/lingua-pupuli/puppet-editor-services/issues/34 for the autocomplete not doing defined types

Raised https://github.com/lingua-pupuli/puppet-editor-services/issues/35 for the modulepath addition

**Comment by jpogran** [comment]
Since the future work this ticket generated are being tracked in individual tickets, with work ongoing, I don't see the reason to keep this ticket open. Closing now, feel free to reopen if I'm wrong
