### ISSUE TITLE
"Go to definition" doens't work

### ISSUE THREAD

**Issue by Sebor** [lingua-pupuli/puppet-vscode#228]
### What Versions are you running?
OS Version: Windows 10
VSCode Version: 1.21.0
Puppet Extension Version: 0.9.0
Puppet Agent Version: 5.3.4
PDK Version (if applicable): 1.4.1.1

### What You Are Seeing?
I use puppet + r10k with "roles-profiles" model. So I have a control repo with all puppet code.
I've faced with one problem - the functionality "go to definition" doesn't work. When I try to go to definition manually (by selecting word and pressing F12) I get message "The definition of blablabla not found". The same behaviour is for any kind of resources - variables, classes, includes, roles, profiles.. In another IDE (pycharm with puppet plugin, for example) it works well.

### What is Expected?
"Go to definition" works (by pressing F12 or clicking on word with CTRL-key)

### How Did You Get This To Happen? (Steps to Reproduce)
There are no additional actions. I just installed extension.

### Output Log
In attachment
[puppet-vscode.txt](https://github.com/jpogran/puppet-vscode/files/1806240/puppet-vscode.txt)

**Comment by glennsarti** [comment]
At the moment, files/manifests etc. **within** the editor are not parsed or processed for things like autocomplete, hover support or GoTo definition.  Only modules in the puppet modulepath are loaded for that.  However this is restriction we're working to overcome.

Technical reasons:  Puppet internally doesn't allow you to "unload" a module, and nor should it.  So imagine you're typing, every time you edit that document  we'd need to stop the ruby process (i.e. the language server) and restart it.  That's a huge overhead and a really bad user experience.  Current thinking is to do the parsing out of process and then cache the results.

**Comment by glennsarti** [comment]
Closing issue and is now being tracked in https://github.com/lingua-pupuli/puppet-editor-services/issues/20
