### ISSUE TITLE
If any host or port is specified use a TCP language client instead of STDIO

### ISSUE THREAD

**Issue by glennsarti** [lingua-pupuli/puppet-vscode#239]
Note - Blocked until #238 is completed.

As part of #238 the default transport will be STDIO.  This means we can change the lang. client behaviour to use the TCP transport if either Port or Host are specified.

https://github.com/jpogran/puppet-vscode/blob/8fdfb7894d08de673bac319991a2499050df97f6/client/src/connection.ts#L76-L82

**Comment by jpogran** [comment]
This is implemented slightly differently than originally written in this. This is now decided by the `puppet.languageclient.protocol` setting. It defaults to `STDIO`, but if you specify `TCP` it will inspect the `puppet.languageserver.host` and `puppet.languageserver.port` configuration settings for what to use to connect to the languageserver. If they aren't set (the default), it will choose it's own port. If they are set, then it will use those settings. This is implemented in PR #292
