### ISSUE TITLE
Incorrect line numbers reported in Problems

### ISSUE THREAD

**Issue by Wookiesneak** [lingua-pupuli/puppet-vscode#245]
### What Versions are you running?
OS Version: Windows 10 (1709)
VSCode Version: 1.21.1 (x64)
Puppet Extension Version: 0.9.0
Puppet Agent Version: 5.3.3
 
### What You Are Seeing?
Problems reported on lines that do not exist, and no other indication where the issue is.
 
### What is Expected?
Correct line numbers for problems
 
### How Did You Get This To Happen? (Steps to Reproduce)
Uncertain; example manifest attached
 
### Output Log
Attached

[outputlog.txt](https://github.com/jpogran/puppet-vscode/files/1853370/outputlog.txt)
![vscode_extension_issue](https://user-images.githubusercontent.com/30609248/37988390-674e7340-31c6-11e8-9481-2b4ac71e449f.jpg)
[vscode_extension_issue.pp.txt](https://github.com/jpogran/puppet-vscode/files/1853371/vscode_extension_issue.pp.txt)

**Comment by glennsarti** [comment]
This can happen when the extension crashes. It doesn't update the problems list.  Did you notice if it said "Starting Error" in the bottom right hand corner?

**Comment by glennsarti** [comment]
Nope nevermind.   It's a CRLF issue

**Comment by glennsarti** [comment]
#176 is a similar issue.   Puppet-lint just released a new gem so this _should_ fix it.  I'll confirm that it does for this manifest too.

**Comment by glennsarti** [comment]
Confirmed this issue is fixed in puppet-lint 2.3.5.  Added a test for this in https://github.com/jpogran/puppet-vscode/pull/246

**Comment by jpogran** [comment]
Closing this as it was releasing in the 0.10.0 milestone
