### ISSUE TITLE
Language server errors when opening a OneDrive Folder or workspace

### ISSUE THREAD

**Issue by rsteenwyk** [lingua-pupuli/puppet-vscode#262]
### What Versions are you running?

OS Version: Windows 10
VSCode Version: 10.0.16299
Puppet Extension Version: 0.10.0
Puppet Agent Version: 5.5.1

### What You Are Seeing?
If I open a folder or a workspace with VS Code where the underlying folders are in OneDrive, the language server is erroring.

I cannot replicate if I remove OneDrive from the equation - so opening a folder that is sitting outside of OneDrive functions just fine.

In TCP lang server output I see:
[Error - 11:29:57 AM] Connection to server is erroring. Shutting down server.

### What is Expected?
Have it run without erroring

### How Did You Get This To Happen? (Steps to Reproduce)
I have my Puppet source in a OneDrive folder, if I do not store the files in OneDrive I have no issue. 

To replicate put a folder in OneDrive with 2 or more .PP files, in VS Code "Open Folder" against that folder. Puppet Lang Server will raise errors and shutdown.

### Output Log
In the logs below, only difference is where the folder is stored. In the failure log the folder is in Onedrive, in success it is not. Folder name and contents remain the same between both.

Failure debug log: https://gist.github.com/rsteenwyk/7969f0f2fec14eacb8b6011c72ce1fdc
Succeses debug log: https://gist.github.com/rsteenwyk/e2681684b591ce20d1a5c40a2608b2fb

**Comment by glennsarti** [comment]
Needs a repro to figure out if this is a lang server or VS Code issue.

**Comment by jpogran** [comment]
VSCode 1.24.1
OneDrive 18,111,0603.0004
Same versions for everything else

It seems to load fine with these versions, and I also tried with the latest master. There were several updates to VSCode since we first worked on this issue. Can you try again with the latest VSCode release?

**Comment by rsteenwyk** [comment]
Away from my main dev machine today, I'll try and get it tested tomorrow.

**Comment by rsteenwyk** [comment]
Confirmed, can no longer replicate this issue running VS Code 1.24.1.

Closing.
