### ISSUE TITLE
Review Settings Names

### ISSUE THREAD

**Issue by jpogran** [lingua-pupuli/puppet-vscode#278]
The configuration settings for the extension need a review to see if they make sense, especially to someone who does not know the ins and outs of VSCode Language Servers.

For example: [puppet,,languageserver.address](https://github.com/lingua-pupuli/puppet-vscode/blob/master/package.json#L276)...what does languageserver mean? What is the difference between that and the new setting we are adding [puppet.languageclient.protocol](https://github.com/lingua-pupuli/puppet-vscode/pull/272/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R275)? What is languageclient or languageserver to the user of our extension?

**Comment by glennsarti** [comment]
Current settings

|  Name | Description |
| ------- | -------- |
| puppet.format.enable | Enable/disable the Puppet formatter |
| puppet.installDirectory  | The fully qualified path to the Puppet agent install directory.  ... |
| puppet.installType | The Puppet Install Type |
| puppet.languageclient.minimumUserLogLevel  | Set the minimum log level tha .... |
| puppet.languageclient.protocol  | protocol  |
| puppet.languageserver.address | The IP address or hostname of the Puppet Language Server to connect to |
| puppet.languageserver.debugFilePath | Set the local Puppet Language Server to send debug information to a file |
| puppet.languageserver.filecache.enable | (Experimental) Enable a persistent file cache for Puppet objects in the Language Server |
| puppet.languageserver.port | The TCP Port of the Puppet Language Server to connect to |
| puppet.languageserver.timeout | The timeout to connect to the local Puppet Language Server |

**Comment by glennsarti** [comment]
First cut at new layout

* I'm not sure about `editorService`.  `LanguageService` maybe? or `language` ?
* I've also added future options in so you get a feel for where they would go

| Name | Description |
| -- | -- |
| `puppet.editorService.debugFilePath` | File path to the editor service log file |
| `puppet.editorService.docker.<future>` | **future** Settings when runing editor services as a docker container |
| `puppet.editorService.enable` | Enable/disable the Puppet Editor Service (aka Language Server) |
| `puppet.editorService.featureFlags` | Array of feature flags to pass to the language server |
| `puppet.editorService.loglevel` | Log level for the editorService (aka language server) |
| `puppet.editorService.protocol` | Protocol to connect to the editor service: STDIO (default), TCP, Docker (Future) |
| `puppet.editorService.tcp.address` | The IP address or hostname of the Puppet Language Server to connect to |
| `puppet.editorService.tcp.port` | The TCP Port of the Puppet Language Server to connect to |
| `puppet.editorService.timeout` | The timeout to connect to the local Puppet Language Server |
| `puppet.format.enable` | Enable/disable the Puppet formatter |
| `puppet.installDirectory ` | The fully qualified path to the Puppet agent install directory.  ... |
| `puppet.installType` | The Puppet Install Type |
| `puppet.lint.<rule>.enable` | **future** Modify per puppet-lint rules |
| `puppet.lint.enable` | Enable/disable the realtime puppet lint tools |
| `puppet.pdk.<setting>` | **future** Enable or configure PDK integration e.g. default author name |

**Comment by glennsarti** [comment]
Updated - Added puppet.path (unknown/unused setting)
