### ISSUE TITLE
Comments parsed instead of ignored

### ISSUE THREAD

**Issue by kaplun** [lingua-pupuli/puppet-vscode#283]
### What Versions are you running?

OS Version: Ubuntu 18.04
VSCode Version: 1.23.1
Puppet Extension Version: 0.10.0
Puppet Agent Version: not installed
PDK Version (if applicable):

### What You Are Seeing?

An single quote within a comment is considered as the start of a new string:
![quote](https://user-images.githubusercontent.com/119349/40968674-73e48c94-68b6-11e8-896f-7f6d2d328817.png)

### What is Expected?
When no single quote is in the comment everything behaves nicely:
![noquote](https://user-images.githubusercontent.com/119349/40968744-97f2b5ca-68b6-11e8-8254-19c2b9af7494.png)

**Comment by glennsarti** [comment]
@kaplun Thanks for the bug report!  I've raised this over in the [syntax highlighting repo](https://github.com/lingua-pupuli/puppet-editor-syntax), and keep this issue open until it's resolved.

**Comment by glennsarti** [comment]
Fixed in https://github.com/lingua-pupuli/puppet-vscode/pull/287 .  Will be available next release.  Closing issue.
