### ISSUE TITLE
Support for #region folding

### ISSUE THREAD

**Issue by neitik** [lingua-pupuli/puppet-vscode#284]
Hello, I would really like to see support for `#region` folding for Puppet manifests, as described here:
https://github.com/Microsoft/vscode-python/issues/33

This is supported out-of-box by VSCode and only a minor change is required to make it work it with Puppet manifests:
```json	
"folding": {
	"offSide": true,
	"markers": {
		"start": "^\\s*#region\\b",
		"end": "^\\s*#endregion\\b"
	}
}
```
The code is taken from aforementioned issue and tested locally.

**Comment by glennsarti** [comment]
There is also an option to add syntax aware folding (as opposed to the default indentation and maker style)

https://code.visualstudio.com/docs/editor/codebasics#_folding
https://code.visualstudio.com/docs/extensionAPI/vscode-api#FoldingRangeProvider

This would require upping the minimum VSCode version to 1.22

Although I'm yet to find a compelling reason to go down this route.  Something to think about.

**Comment by glennsarti** [comment]
Fixed and will be available next release!

**Comment by neitik** [comment]
Great, thank you :+1: 

I think we can close this.
