### ISSUE TITLE
Feature Request - Add snippets for adding modules in a PuppetFile

### ISSUE THREAD

**Issue by glennsarti** [lingua-pupuli/puppet-vscode#288]
Add snippets for adding modules to a Puppetfile e.g.

e.g. From the forge
`mod 'puppetlabs-puppet_agent'`

e.g. From github
```
mod 'puppet_agent',
  :git => 'https://github.com/glennsarti/puppetlabs-puppet_agent',
  :ref => 'log-for-windows'
```

**Comment by cdenneen** [comment]
+ .fixtures.yml

**Comment by glennsarti** [comment]
@cdenneen Did you want the language server to understand .fixtures.yml?

**Comment by cdenneen** [comment]
Yes I think because Puppetfile and .fixtures.yml are so similar it would be
good to edit them but validate syntax (no comma, ref not tag, etc)

**Comment by glennsarti** [comment]
I'll have to dig around a bit for that.  It gets tricky injecting features into other languages (in this case the YAML language).  Typically extensions own the entire language or none of it.

**Comment by glennsarti** [comment]
This is blocked on #295, which is block on #412 

We need the connection manager refactored, so we can add Puppetfile as a language which shares the same LanguageServer etc.

**Comment by glennsarti** [comment]
@jpogran Can we take this out of the 0.14 project and milestone?

**Comment by jpogran** [comment]
@glennsarti makes sense to me, removing.

**Comment by jpogran** [comment]
This depends on #295 being implemented first, so taking it out of the milestones
