### ISSUE TITLE
Add Puppetfile as a contributing langauge

### ISSUE THREAD

**Issue by glennsarti** [lingua-pupuli/puppet-vscode#295]
The language server is in the process of understanding Puppetfile's.

https://github.com/lingua-pupuli/puppet-editor-services/issues/28 and https://github.com/lingua-pupuli/puppet-editor-services/pull/25

However this has shown an issue in the extension.  The current package.json only associates `*.pp` and `*.epp` files to the puppet extension (https://github.com/lingua-pupuli/puppet-vscode/blob/35b56a3458376857c764851cad14170b5d104bfd/package.json#L56-L69).  Now, you can manually assign `Puppetfile` as a Puppet language file, which I did for my testing BUT...

This means I end up with all the PDK commands and Puppet Resource and Node Graph commands which make no sense in a Puppetfile.  Also it gets the syntax coloring, hardcoded snippets and bracketing.  Fortunately Puppet DSL is similar to Ruby langauge (Puppetfile is just ruby) however it's not always the case.

So the trouble is, how to separate the two languages but still give meaningful insights to Puppetfiles's (autocomplete, hover, validation etc.)

## Option 1 - Build a Node based language server (👎)

* There are some projects out there to parse and cross-compile ruby into Javascript but it's going to be hard work
* Would need to write our own Forge API handler

## Option 2 - Build a new Puppetfile Extension (👎)

* Yes this could be done, but it will involve a lot of duplicate work e.g. All of the ruby instantiation methods etc.  May as well just use what we already have

## Option 3 - Add a new contributed language and share the Language Server (👍)

Add a new language contribution to this extension, but share the Language Server.   A brief look at the extension code shows we can contribute multiple languages and still have a single instance of the language server connection.  We would need to refactor some of the code to handle multiple `langIDs` (e.g. the Puppet Status Bar), and some code would need guards on the commands (e.g. `"when": "resourceLangId == 'puppet'")

We could then have separate syntax coloring, Puppetfile only commands, bracketing etc. for the two languages types; `puppet` and `puppetfile`

What do you think?

**Comment by jpogran** [comment]
I see Option 3 as the only way. I think it's how vscode expects you to handle these things.

**Comment by michaeltlombardi** [comment]
I'm also in favor of option three, not sure either of the others make any sense given the context.
