### ISSUE TITLE
Linting does not use .puppet-lint.rc

### ISSUE THREAD

**Issue by setaou** [lingua-pupuli/puppet-vscode#304]
### What Versions are you running?

OS Version: Ubuntu 18.04
VSCode Version: 1.24.1
Puppet Extension Version: 0.10.0
Puppet Agent Version: 4.10.4

### What You Are Seeing?
I have a .puppet-lint.rc file at the root of my workspace containing only the following line : 
--no-140chars-check

If I use the puppet-lint command from a terminal, it uses this config file and ignores the warnings about long lines. However, the linting in vscode still shows the warnings.

### What is Expected?
The linting in vscode should enforce the options set in .puppet-lint.rc.

**Comment by glennsarti** [comment]
Is this inside a module or control repository?

**Comment by setaou** [comment]
It is at the root of the repository (which is the whole /etc/puppet).

**Comment by glennsarti** [comment]
Migrated this to editor services - 
https://github.com/lingua-pupuli/puppet-editor-services/issues/43
