### ISSUE TITLE
Feature Request: Force linting across all files 

### ISSUE THREAD

**Issue by tdallmann** [lingua-pupuli/puppet-vscode#306]
**As a** user

**I would like to** run linter against all files in the currently opened folder structure

**so that I** don't have to open each and every file to check the entire project.

Currently linting only occurs as a file is edited.  But when reviewing another developers work it is often useful to ensure that no linter errors have been introduced.  I would like to be able to checkout a branch and run linter across all files without having to open every file for edit.

**Comment by jpogran** [comment]
Thanks for the excellently formatted user story, it really helps!

We'll have some work to do to implement this, as it's not an easy thing to accomplish in VSCode right now for us. Most of what we do is file specific right now, but we're working on making it more multi-file aware.

As a stopgap, you can use the PDK right now to accomplish this. It will do a little more than you ask for, but running `pdk validate` will lint all files in the directory it is run. Predictably, this will output the errors to the terminal and not enter them into the VS Code Problems Pane. This isn't exactly what you want inside VSCode, but it does most of what you want outside it. You can then open up the file directly in VSCode by running `code path/to/file.pp` after you inspected the list returned from `pdk validate`.

**Comment by jpogran** [comment]
@TJM I had meant you could run `pdk validate` now, it's just not a built in VSCodepalette command. In either the PDK terminal tab, or in a regular terminal tab inside VSCode, you can run pdk commands directly.

**Comment by jpogran** [comment]
@tdallmann The way the VSCode internals work right now, it's not possible for us at this time to make our extension lint all the files at once.

As mentioned before, you can use `pdk validate` to do this. You can use `pdk validate` inside VSCode (either using the integrated terminal or the Command palette) to run against the entire workspace and see the list of files that have linting errors. This list will be `clickable` inside the VSCode terminal, so you can pop to each file to inspect the errors. This is the best we can do at this time.

@TJM `pdk validate` is now part of the VSCode command palatte, so you can execute it inside VSCode.

I'm going to close this issue out, if you feel there is more to do here let me know.
