### ISSUE TITLE
Path auto-detection does not work on *nix and mac

### ISSUE THREAD

**Issue by jpogran** [lingua-pupuli/puppet-vscode#307]
With the new configuration class, resolving paths on *nix and mac installs does not work.

The install path for Puppet in Windows is `$env:ProgramFiles\Puppet Labs\Puppet`, but in the Mac and *nix packages it's `/opt/puppetlabs` (unless you're arch linux where it's `/usr/bin/puppet` but let's ignore that for now). This is important because the extension previously assumed it was `/opt/puppetlabs/puppet` on *nix and Mac, which would then be resolved to `/opt/puppetlabs/puppet/puppet` when the extension later on resolved the directory for the Puppet binaries.

**Comment by glennsarti** [comment]
Closed by merge
