### ISSUE TITLE
Update viz.js to latest version (2.0)

### ISSUE THREAD

**Issue by glennsarti** [lingua-pupuli/puppet-vscode#309]

**Comment by jpogran** [comment]
removed from https://github.com/orgs/lingua-pupuli/projects/3 as it does not need to be completed in order to use vscode 1.2X

**Comment by glennsarti** [comment]
Perhaps use d3-graphviz?

**Comment by glennsarti** [comment]
Adding awaiting label to exempt it from stale issues

**Comment by jpogran** [comment]
PR #603 updates the viz.js library to latest. However, the source repo https://github.com/mdaines/viz.js is archived. This likely means its abandoned and we should eventually move off it.

**Comment by jpogran** [comment]
This is superseded by #613
