### ISSUE TITLE
Auto-fix on save

### ISSUE THREAD

**Issue by walles** [lingua-pupuli/puppet-vscode#312]
**As a** user

**I would like to** automatically have `puppet-lint --fix` run every time I save a file

**so that I** don't have to fix `=>` indentation errors manually after I add / change an option

Note: This should be optional.

**Comment by glennsarti** [comment]
Have you tried using the `editor.formatOnSave` setting?  This instructs VSCode to call the "Format Document" command on save.

`Format Document` for puppet files is the same as `puppet-lint --fix`

**Comment by walles** [comment]
Yes, that actually did help.

Not very obvious but does do the trick.

Tentatively I feel that I would prefer enabling this only for Puppet, but I'll just leave format-on-save enabled for now and we'll see.

Thanks @glennsarti!
