### ISSUE TITLE
Abstract Puppet and Ruby path detection to allow PDK use

### ISSUE THREAD

**Issue by jpogran** [lingua-pupuli/puppet-vscode#315]
There was alot of work done in https://github.com/lingua-pupuli/puppet-vscode/pull/272, among other commits to improve the detection and configuration of settings needed for the LanguageServer to run and allow us to change things like TCP or STDIO without changing half the code base. However it stopped short of enabled us to choose PDK or Puppet-Agent as the Puppet and Ruby source easily in a supportable way.

This issue will refactor the path detection and resolution for the Puppet and Ruby paths to allow using the PDK as a source instead of the Puppet Agent.

It will:

- If a user specifies a custom path, it will use that path and stop resolution
- If a user does not specify a custom path, it will attempt to use PDK first
- If PDK is not found, it will attempt to use Puppet Agent
- If no valid path is found, it will throw an error and not attempt to load the language server

Note, that in order to do this we have to account for the different installation paths in Windows, Linux, and Mac *and* the different paths between PDK and Puppet-Agent.

**Comment by glennsarti** [comment]
Fixed by https://github.com/lingua-pupuli/puppet-vscode/pull/330
