### ISSUE TITLE
Allow PDK New Class right-click menu option appear when right-clicking places other than a .pp file

### ISSUE THREAD

**Issue by davidalexander83** [lingua-pupuli/puppet-vscode#322]
As a VSCode user, I would like to right-click and be able to select "PDK New Class", regardless of whether I'm in a .pp file Editor or not.

When first initialising a module, no .pp files exist, and as such we can't use the PDK New Class right-click menu item. This can be done through the terminal of course, but it would be neat to have a right-click option around as well.

**Comment by jpogran** [comment]
Thanks for the feedback @davidalexander83. The reason the restriction is there is that `PDK New Class` has to have a module folder 'present' that was created by the PDK, or it doesn't work. The only way at the time we could ensure we knew that there was a PDK module present as the working directory was to only activate when a Puppet file was opened. We'll work on the rules selection to see if we can open it up.

When you suggest a right click menu, do you mean the menu you get when you right click anywhere in the editor? Or the menu you get when you right click on a folder (like what you get when you go to create a new file)?
