### ISSUE TITLE
Allow disabling of language server

### ISSUE THREAD

**Issue by snoopdouglas** [lingua-pupuli/puppet-vscode#335]
I get this error whenever I open a `.pp`:

```
Could not find a valid Puppet installation at '/opt/puppetlabs/puppet'. While syntax highlighting and grammar detection will still work, intellisense and other advanced features will not.
```

I'm happy just using the syntax highlighting and grammar detection (as stated), and not having VS Code interact with a language server at all.

I seem to recall that there used to be an option to turn it off - but can no longer find it.

**Comment by jpogran** [comment]
@snoopdouglas I'm pretty sure there was never an option to disable the language server. We recently added that error message as a way to better notify users when functionality would be degraded, whereas before there wasn't an obvious error message.

It's pretty reasonable to want to disable it, we'll add it to the board.

**Comment by glennsarti** [comment]
+1.  We will be revisiting the settings we currently have so this would be a good time.

**Comment by jpogran** [comment]
@snoopdouglas just letting you know, we're planning on adding this to the next release.
