### ISSUE TITLE
RubyHelper code modifies existing environment variables when starting language server

### ISSUE THREAD

**Issue by glennsarti** [lingua-pupuli/puppet-vscode#343]
The code in https://github.com/lingua-pupuli/puppet-vscode/blob/0e77ea0719ef6847a0a673860be5f2c8141229ba/src/rubyHelper.ts#L22 unfortunately passes a reference to the current process environment, not a duplicate of it.  That means later on in https://github.com/lingua-pupuli/puppet-vscode/blob/0e77ea0719ef6847a0a673860be5f2c8141229ba/src/rubyHelper.ts#L41-L57 we are actually affecting the environment variables of the VSCode parent process, not just the spawning child process.

The code at https://github.com/lingua-pupuli/puppet-vscode/blob/0e77ea0719ef6847a0a673860be5f2c8141229ba/src/rubyHelper.ts#L22 should clone the environment instead.

**Comment by jpogran** [comment]
So this doesn't work on mac. I get `The terminal process terminated with exit code: 1` way before anything even starts logging. Investigating

**Comment by jpogran** [comment]
We need to do a `npm install` and commit the package-lock.json. It was missed at some point.
