### ISSUE TITLE
Extension keeps running after quitting VSCode & using 100% CPU

### ISSUE THREAD

**Issue by KTamas** [lingua-pupuli/puppet-vscode#350]
### What Versions are you running?

OS Version: OSX 10.13.6
VSCode Version: Insiders latest
Puppet Extension Version: 0.11.0
Puppet Agent Version: 5.5.1

### What You Are Seeing?

The language server keeps running in the background using 100% CPU even after quitting VSCode. Sometimes multiple instances. 

Example:
```
~ ps aux|grep ruby
KTamas           43686  98.8  0.9  4455732 148024   ??  R    11:02AM  99:19.55 ruby /Users/KTamas/.vscode-insiders/extensions/jpogran.puppet-vscode-0.11.0/vendor/languageserver/puppet-languageserver --stdio --timeout=10 --local-workspace=[censored] --debug=/Users/KTamas/puppetlslog.txt
```
### What is Expected?

Not killing my battery... :) If this is because I'm running the insiders version of VSCode feel free to close this, I understand.

### How Did You Get This To Happen? (Steps to Reproduce)

Start VSCode, open a puppet manifest, wait for things to load, do work, quit VSCode, watch your battery die.

### Output Log

```
I, [2018-08-15T11:02:22.144537 #43686]  INFO -- : Language Server is v0.12.0
I, [2018-08-15T11:02:22.144900 #43686]  INFO -- : Using Puppet v5.5.1
I, [2018-08-15T11:02:22.145071 #43686]  INFO -- : Initializing Puppet Helper Cache...
D, [2018-08-15T11:02:22.145283 #43686] DEBUG -- : Initializing Document Store...
I, [2018-08-15T11:02:22.145474 #43686]  INFO -- : Initializing settings...
I, [2018-08-15T11:02:22.148895 #43686]  INFO -- : Starting RPC Server...
D, [2018-08-15T11:02:22.149543 #43686] DEBUG -- : Using STDIO
I, [2018-08-15T11:02:22.149929 #43686]  INFO -- : Client has connected to the language server
D, [2018-08-15T11:02:22.150182 #43686] DEBUG -- : STDIOSRV: Starting STDIO server...
D, [2018-08-15T11:02:22.150534 #43686] DEBUG -- : --- INBOUND

[...]

I, [2018-08-15T12:03:54.827165 #43686]  INFO -- : Received textDocument/didClose notification.
D, [2018-08-15T12:03:55.437141 #43686] DEBUG -- : --- INBOUND
{"jsonrpc":"2.0","id":68,"method":"shutdown","params":null}
---
D, [2018-08-15T12:03:55.437469 #43686] DEBUG -- : Received shutdown method
D, [2018-08-15T12:03:55.437717 #43686] DEBUG -- : --- OUTBOUND
{"jsonrpc":"2.0","id":68,"result":null}
---
D, [2018-08-15T12:03:55.437986 #43686] DEBUG -- : --- INBOUND
{"jsonrpc":"2.0","id":69,"method":"shutdown","params":null}
---
D, [2018-08-15T12:03:55.438259 #43686] DEBUG -- : Received shutdown method
D, [2018-08-15T12:03:55.438486 #43686] DEBUG -- : --- OUTBOUND
{"jsonrpc":"2.0","id":69,"result":null}
---
```

**Comment by glennsarti** [comment]
Thanks @KTamas !!

Fixed in https://github.com/lingua-pupuli/puppet-editor-services/pull/50

Pending a release of the extension

**Comment by KTamas** [comment]
oh awesome thanks, this was driving me crazy. hope it gets released soon, then.

**Comment by jpogran** [comment]
Apologies for the delay in new release, we have some really neat things coming in next release. We hope to have a target date this week

**Comment by jpogran** [comment]
@KTamas This was included in the release today. Let us know if this fixes it for you.

**Comment by XerockXMG** [comment]
I'm seeing the same issues with 0.11.1. I'm running on Ubuntu 18.04 and VSCode:
`1.24.0
6a6e02cef0f2122ee1469765b704faf5d0e0d859
x64`

Also seems to crash VSCode's Extension Host after a couple minutes.

**Comment by jpogran** [comment]
@XerockXMG The `puppet.puppetAgentDir` expects the path to the install directory (`/opt/puppetlabs`), not the binary directory (`/opt/puppetlabs/puppet/bin`) so that could explain the problems there.

**Comment by jpogran** [comment]
@KTamas is this still an issue for you?

@XerockXMG Did specfying the path like I suggest help you?
