### ISSUE TITLE
Refactor code and group features and providers together

### ISSUE THREAD

**Issue by glennsarti** [lingua-pupuli/puppet-vscode#373]
**As a** Developer

**I would like to** group extension features into a singular file

**so that I** I don't need to have to modify multiple files when adding features

For example,
Puppet command text + Feature + register command etc.. Ideally it should just be a single feature file e.g.
 PuppetNodeGraph or PuppetResourceCommand.

- [x] Node Graph
- [x] Puppet Resource Command
- [x] Format Document
- [x] PDK NewClass Command
- [x] PDK NewModule Command
- [x] PDK NewTask Command
- [x] PDK Test Command
- [x] PDK Validate Command

**Comment by glennsarti** [comment]
Raised #370 for the node graph

**Comment by glennsarti** [comment]
PR #374 is for the Format Document provider.

**Comment by glennsarti** [comment]
@jpogran I think this can be closed now.

**Comment by jpogran** [comment]
![yes](https://media.giphy.com/media/3ohhweiVB36rAlqVCE/giphy.gif)
