### ISSUE TITLE
Support Puppet Agent v6.x

### ISSUE THREAD

**Issue by glennsarti** [lingua-pupuli/puppet-vscode#384]
Puppet 6 has breaking changes.  Make sure the extension works with Puppet 6 agent. PDK will come later.

- [x] inline linting
- [x] format document
- [x] Node Graph  (failing)
- [x] Hover, Autocomplete
- [x] Debug. Known issues with Puppet 6

**Comment by glennsarti** [comment]
So I tested the current extension code with master of puppet-editor-services (which includes https://github.com/lingua-pupuli/puppet-editor-services/pull/53).  

I used the Puppet-Agent 6.0.2 msi package and the extension appeared to work fine-ish

![image](https://user-images.githubusercontent.com/5819622/46514273-94f89e00-c88f-11e8-8821-7a458258e014.png)

**Comment by glennsarti** [comment]
The node graph failure wasn't related to Puppet 6 but due to #388

**Comment by glennsarti** [comment]
@jpogran I think we can close this issue unless you can think of something else to test.

**Comment by jpogran** [comment]
Agreed
