### ISSUE TITLE
hover not working on puppet resource names and autocompletion not working

### ISSUE THREAD

**Issue by af6140** [lingua-pupuli/puppet-vscode#391]
### What Versions are you running?

OS Version: ubuntu 16.04
VSCode Version: 1.28.0
Puppet Extension Version:  0.12.0
Puppet Agent Version: 5.5.6
PDK Version (if applicable):

### What You Are Seeing?
1. when hovering on resource, nothing happens
2. autocompletion not working
### How Did You Get This To Happen? (Steps to Reproduce)
1. Install as documented
2. Open puppet class file
3. hover on resources nothing happened
### Output Log
Illegal argument, contents must be defined: Error: Illegal argument, contents must be defined
	at new <anonymous> (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:315:400)
	at asHover (/home/dwang/.vscode/extensions/jpogran.puppet-vscode-0.12.0/node_modules/vscode-languageclient/lib/protocolConverter.js:63:16)
	at <anonymous>

**Comment by af6140** [comment]
After multiple restarts and enabling debugging, suddenly it starrted working.

**Comment by glennsarti** [comment]
Thanks for the great bug report. This is a little worrying but we'll keep an eye on it.  Particularly as it's for a newly released VSCode version.

@af6140 Did you want to close the issue for now? or keep it open for a few days and see if it comes back?

**Comment by af6140** [comment]
@glennsarti, thanks for response, you can close it now.

One extra question, for custom resources etc, will the hovering documentation popup work? Does the language server load extra modules?

**Comment by glennsarti** [comment]
> custom resources etc, will the hovering documentation popup work? 

Not yet. https://github.com/orgs/lingua-pupuli/projects/5 is tracking the work to get that feature in

> Does the language server load extra modules?

The language server will load whatever is in your modulepath as per your puppet.conf file.  That said it's on my list of things to do, to make it a VSCode setting so you can override the modulepath in your editor
