### ISSUE TITLE
enable ability to choose agent version when using pdk

### ISSUE THREAD

**Issue by isaiahfrantz** [lingua-pupuli/puppet-vscode#404]
OS Version: fedora 28
VSCode Version: insiders (current as of 10/19/18, but have been seeing this since I tried --puppet-dev tests)
Puppet Extension Version: 0.12.0
Puppet Agent Version: I want 5.3.3 as my default but am getting 6.0.2 now
PDK Version (if applicable): 1.7.1

### What You Are Seeing?
After running `pdk test unit --puppet-dev` to test against the latest agent I am now getting v6.0.2 in the status bar

### What is Expected?
I have the following env variables set to lock the agent to my current prod version during cli tests:
```
PUPPET_GEM_VERSION=5.3.3
PDK_PUPPET_VERSION=5.3.3
```

### How Did You Get This To Happen? (Steps to Reproduce)
on external cli in a module dir that is pdk compliant/converted and has rspec tests: 
# run test with agent version specified via env var
`export PDK_PUPPET_VERSION=5.3.3; pdk test unit`
# unset and run against future version (6.0.2 as of today)
`unset PDK_PUPPET_VERSION; pdk test unit --puppet-dev`
# set env var and start code
`export PDK_PUPPET_VERSION=5.3.3; code`

After selecting a pp file, it will say that the agent version is 6.0.2
I am assuming that the extension is using the highest alphanumeric version to use but it would be nice if we could set a default version to use from those detected
```
[localhost pdk]$ ls -d /opt/puppetlabs/pdk/private/puppet/ruby/*/gems/puppet-[0-9]*|tail -1
/opt/puppetlabs/pdk/private/puppet/ruby/2.5.0/gems/puppet-6.0.2
```
```
[localhost pdk]$ ll -d /opt/puppetlabs/pdk/private/puppet/ruby/*/gems/puppet-[0-9]*
drwxr-xr-x. 10 root root 4096 Oct 10 09:56 /opt/puppetlabs/pdk/private/puppet/ruby/2.1.0/gems/puppet-4.7.1
drwxr-xr-x. 10 root root 4096 Oct 10 09:56 /opt/puppetlabs/pdk/private/puppet/ruby/2.1.0/gems/puppet-4.8.2
drwxr-xr-x. 11 root root 4096 Oct 10 09:56 /opt/puppetlabs/pdk/private/puppet/ruby/2.1.0/gems/puppet-4.9.4
drwxr-xr-x. 11 root root 4096 Oct 10 09:56 /opt/puppetlabs/pdk/private/puppet/ruby/2.4.0/gems/puppet-5.0.1
drwxr-xr-x. 11 root root 4096 Oct 10 09:56 /opt/puppetlabs/pdk/private/puppet/ruby/2.4.0/gems/puppet-5.1.0
drwxr-xr-x. 11 root root 4096 Oct 10 09:56 /opt/puppetlabs/pdk/private/puppet/ruby/2.4.0/gems/puppet-5.2.0
drwxr-xr-x. 11 root root 4096 Oct 10 09:56 /opt/puppetlabs/pdk/private/puppet/ruby/2.4.0/gems/puppet-5.3.7
drwxr-xr-x. 11 root root 4096 Oct 10 09:56 /opt/puppetlabs/pdk/private/puppet/ruby/2.4.0/gems/puppet-5.4.0
drwxr-xr-x. 11 root root 4096 Oct 10 09:56 /opt/puppetlabs/pdk/private/puppet/ruby/2.4.0/gems/puppet-5.5.6
drwxr-xr-x. 11 root root 4096 Oct 10 09:56 /opt/puppetlabs/pdk/private/puppet/ruby/2.5.0/gems/puppet-6.0.2
```

**Comment by glennsarti** [comment]
You are correct, the environment variables will have no effect.  I've added this is as a feature request.

**Comment by glennsarti** [comment]
So some background information so I don't forget it.

for Windows;
``` batch
@ECHO OFF

SET PUPPET_BASEDIR=C:\Progra~1\Puppet~1\DevelopmentKit
SET PUPPET_NIXBASEDIR=C:/Progra~1/Puppet~1/DevelopmentKit

SET DEVKIT_BASEDIR=%PUPPET_BASEDIR%
SET RUBY_DIR=%DEVKIT_BASEDIR%\private\ruby\2.4.4
SET RUBYLIB=%PUPPET_NIXBASEDIR%/lib

SET PATH=%DEVKIT_BASEDIR%\bin;%RUBY_DIR%\bin;%PATH%
SET RUBYOPT=rubygems

SET GEM_HOME=%PUPPET_NIXBASEDIR%/share/cache/ruby/2.4.0
SET GEM_PATH=%DEVKIT_BASEDIR%\private\ruby\2.4.4\lib\ruby\gems\2.4.0;%PUPPET_NIXBASEDIR%/share/cache/ruby/2.4.0;%PUPPET_BASEDIR%\private\puppet\ruby\2.4.0
```

And doing a simple gem query shows there are multiple versions there;
``` batch
C:\Source>gem list puppet

*** LOCAL GEMS ***

puppet (6.0.2 x64-mingw32, 5.5.6 x64-mingw32, 5.4.0 x64-mingw32, 5.3.7 x64-mingw32, 5.2.0 x64-mingw32, 5.1.0 x64-mingw32, 5.0.1 x64-mingw32)
puppet-debugger (0.10.0)
puppet-lint (2.3.6)
puppet-module-win-default-r2.4 (0.3.12)
puppet-module-win-dev-r2.4 (0.3.12)
puppet-resource_api (1.6.0)
puppet-strings (2.1.0)
puppet-syntax (2.4.1)
puppet_pot_generator (1.0.1)
puppetlabs_spec_helper (2.11.0)
rspec-puppet (2.7.1)
rspec-puppet-facts (1.9.0)
semantic_puppet (1.0.2)
```

Trying to figure out how to tell ruby to load a specific gem version.  We're not using bundler, and can't

**Comment by glennsarti** [comment]
so this simple ruby script does see, to show I can load a specific version

``` ruby
require 'puppet'

puts Puppet.version # Shows 6.0.2
```

``` ruby
gem 'puppet', '5.3.7'

require 'puppet'

puts Puppet.version # Shows 5.3.7
```

**Comment by glennsarti** [comment]
Simple ruby script to output the current puppet versions in JSON onto STDOUT

``` ruby
require 'rubygems'
require 'json'

puts Gem::Specification
  .select { |item| item.name.downcase == 'puppet' }
  .map { |item| item.version }
  .to_json
```

**Comment by jpogran** [comment]
Choosing which version is loaded has been added to the extension in 0.18. More information about how to use this is in https://github.com/lingua-pupuli/puppet-vscode#configure-extension-to-use-pdk. I'm closing this issue now, but feel free to respond if this does not work for you
