### ISSUE TITLE
README.md specifies deprecated param to enable logging

### ISSUE THREAD

**Issue by SinFulNard** [lingua-pupuli/puppet-vscode#405]
### What Versions are you running?

OS Version: macOS 10.13.6
VSCode Version: 1.28.2
Puppet Extension Version: 0.12.0
Puppet Agent Version: N/A 
PDK Version (if applicable): 1.7.0

### What You Are Seeing?
Attempting to enable logs to troubleshoot extension crashing. Using param: `"puppet.languageserver.debugFilePath": "/some/dir/puppet-logs/log.txt",` 

![image](https://user-images.githubusercontent.com/434752/47280270-31a59480-d621-11e8-8a21-3a11951a9e27.png)

### What is Expected?
No warning from using a param from README.md

### How Did You Get This To Happen? (Steps to Reproduce)
Followed the steps from README.md

### BONUS
The following link appears broken when I raise an issue:

"For information how to capture verbose logs, look [here](https://github.com/lingua-pupuli/puppet-vscode/tree/master/client#2-capture-verbose-logs-and-send-them-to-us)"

![image](https://user-images.githubusercontent.com/434752/47280306-6f0a2200-d621-11e8-9c8b-041ca2433c0c.png)

**Comment by glennsarti** [comment]
Thanks for the bug report @SinFulNard .

I'll be putting up a fix for the debugFilePath error.

However I can't seem to find the other link which is broken.  Where abouts did you see that link?

"For information how to capture verbose logs, look here"

**Comment by SinFulNard** [comment]
No probs @glennsarti !

The second link is in the template when a user selects -> New Issue -> Bug Report.
`### Output Log

`

**Comment by glennsarti** [comment]
Found it.  Thanks.  Fix is up.

**Comment by SinFulNard** [comment]
Thanks! I've updated my settings param to match and confirmed the warning is now gone.
