### ISSUE TITLE
Puppet syntax coloring and problem detection fooled by hash character in regex

### ISSUE THREAD

**Issue by tmalaher** [lingua-pupuli/puppet-vscode#410]
Issue Type: <b>Bug</b>

This line:
`if 'foo' =~ /^#bar/ {`

Will be colored green (comment color) from the # character to the end of the line.
This also causes the problem parser to become confused about the block nesting level (since the opening curly brace was taken as part of a comment) and the rest of the file is reported as having spurious errors like:
__Could not parse for environment *root: Syntax error at ...__

Extension version: 0.12.0
VS Code version: Code 1.28.2 (7f3ce96ff4729c91352ae6def877e59c561f4850, 2018-10-17T00:23:51.859Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.90GB (5.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by glennsarti** [comment]
Thanks @tmalaher .  That's an interesting one.  The `root: Syntax error at ...` suggests that it's a syntax error. I'll try and reproduce the problem.

**Comment by glennsarti** [comment]
Highlighting;
![image](https://user-images.githubusercontent.com/5819622/47436854-ec789280-d7d9-11e8-9cb1-9c16706d91ef.png)

**Comment by glennsarti** [comment]
@tmalaher I suspect the `Could not parse for environment *root: Syntax error at ...` is not related.  Can you post your entire script?

**Comment by glennsarti** [comment]
Raised https://github.com/lingua-pupuli/puppet-editor-syntax/issues/8 to track the syntax highlighting issue.

**Comment by tmalaher** [comment]
I have since refactored things so that the regex is done in a facter and the .pp file no longer has the regex, just a simple boolean check...

Now when I try to reproduce the parse error in a freshly created .pp file I am unable to do so.

But at the time of the original report I could trigger/suppress the parse error by changing the # character to a . and back again, so it seemed related.

Let's drop the parser issue for now, until I'm able to reproduce it, if at all.

**Comment by glennsarti** [comment]
Ok I'll close this issue for now and track the work in the puppet-editor-syntax repo.
