### ISSUE TITLE
Remove internal information from the README

### ISSUE THREAD

**Issue by glennsarti** [lingua-pupuli/puppet-vscode#411]
In the README we list the symbols we support, but we also list the internal Puppet Pops type.  Users don't actually know what that is, indeed most people don't care.

I think it should be removed, and just list the common names e.g.

`Supported symbols are Class, Defined Types, Attributes and Variables`

Instead of;

Supported symbols:

Symbol | Puppet Class
 -- | --
Class |  `Puppet::Pops::Model::HostClassDefinition`
Defined Type | `Puppet::Pops::Model::ResourceTypeDefinition`
Attribute | `Puppet::Pops::Model::AttributeOperation`
Variable | `Puppet::Pops::Model::AssignmentExpression`

**Comment by glennsarti** [comment]
Interested in your opinion @michaeltlombardi

**Comment by michaeltlombardi** [comment]
I concur with removing the puppet class information, only the symbols really matter to the end user.

**Comment by jpogran** [comment]
Complete
