### ISSUE TITLE
Restart puppet language server menu missing

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [lingua-pupuli/puppet-vscode#466]
### What Versions are you running?

OS Version: Windows 10, 1809
VSCode Version: 1.30.2
Puppet Extension Version: 0.15.1
Puppet Agent Version: 5.4.0
PDK Version (if applicable):

### What You Are Seeing?

there used to be a second menu item in the popup list that allowed you to force a language server/ extension restart

![missingmenu](https://user-images.githubusercontent.com/22965146/51326962-433ee280-1a3e-11e9-838f-b5ad6a669feb.png)

### What is Expected?

menu item that lets me restart the langauge server 

### How Did You Get This To Happen? (Steps to Reproduce)

click on puppet language server icon

![button](https://user-images.githubusercontent.com/22965146/51326956-3fab5b80-1a3e-11e9-81db-2f0c3df1dfa8.png)

**Comment by jpogran** [comment]
Hi @jgrammen-agilitypr I removed that functionality in https://github.com/lingua-pupuli/puppet-vscode/commit/d13f79d350734f78c11b1ffdad0838c275ff3053. You can still accomplish that same effect by reloading the VSCode window as described [here](https://github.com/lingua-pupuli/puppet-vscode#reloading-the-puppet-vscode-extension)

**Comment by jgrammen-agilitypr** [comment]
Thank you for the solution.
