### ISSUE TITLE
No such file or directory @ dir_s_mkdir

### ISSUE THREAD

**Issue by rogermartensson** [lingua-pupuli/puppet-vscode#485]
### What Versions are you running?

OS Version: Windows 10
VSCode Version: 1.31.1
Puppet Extension Version:
Puppet Agent Version:
PDK Version (if applicable): 1.7.1

### What You Are Seeing?
Server doesn't start. Errors in the output.

### What is Expected?
Expects no error and server running.

### How Did You Get This To Happen? (Steps to Reproduce)
Surfaced after installing 0.17.0. Doesn't disappear after a restart of VSCode

### Output Log
The directory do exists. H: is a network share.

C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:232:in `mkdir': No such file or directory @ dir_s_mkdir - H:/.puppetlabs (Errno::ENOENT)
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:232:in `fu_mkdir'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:210:in `block (2 levels) in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:208:in `reverse_each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:208:in `block in mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:193:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.5.1/lib/ruby/2.5.0/fileutils.rb:193:in `mkdir_p'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.0.2-x64-mingw32/lib/puppet/settings.rb:363:in `create_ancestors'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.0.2-x64-mingw32/lib/puppet/settings.rb:348:in `block in initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.0.2-x64-mingw32/lib/puppet/settings.rb:347:in `each'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.0.2-x64-mingw32/lib/puppet/settings.rb:347:in `initialize_app_defaults'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.0.2-x64-mingw32/lib/puppet.rb:150:in `do_initialize_settings_for_run_mode'
	from C:/Program Files/Puppet Labs/DevelopmentKit/private/puppet/ruby/2.5.0/gems/puppet-6.0.2-x64-mingw32/lib/puppet.rb:142:in `initialize_settings'
	from c:/Users/rogmar/.vscode/extensions/jpogran.puppet-vscode-0.17.0/vendor/languageserver/lib/puppet_languageserver.rb:143:in `init_puppet'
	from c:/Users/rogmar/.vscode/extensions/jpogran.puppet-vscode-0.17.0/vendor/languageserver/puppet-languageserver:10:in `<main>'
[Error - 09:00:47] Connection to server got closed. Server will not be restarted.

**Comment by rogermartensson** [comment]
I had this error for some time but now it works. So the problems was not the extension. I must have been something else.

**Comment by Yanbo-Zhu** [comment]
See  https://stackoverflow.com/questions/10815328/ruby-gems-home-on-windows

If HOME environment variable is not set, Ruby tries to use a combination of HOMEDRIVE and HOMEPATH (e.g. the unaccessible network drive) and fails.

Workaround: On the command line, execute SET HOME=%USERPROFILE%, which will tell Ruby to use your user profile directory (C:\Users\xyz) as the home directory.
