### ISSUE TITLE
When using a regex in a switch statement, the syntax highlighting is broken.  

### ISSUE THREAD

**Issue by thehackadmin** [lingua-pupuli/puppet-vscode#487]
When using a regex in a switch statement, the syntax highlighting is broken.  

`$expand_cmd = $current_muleee_file ? {
  /\.tar\.gz$/ => "/usr/bin/sudo tar -zx -f ${mulesoft_home}/${current_muleee_file} -C ${mulesoft_home}",
  /\.zip$/     => "/usr/bin/sudo unzip ${mulesoft_home}/${current_muleee_file} -d ${mulesoft_home}",
  default      => "not confiugred to use this type of file: ${current_muleee_file}"
}
`
Is valid... maybe not great, but valid.  (don't judge me!   lol) But it looks like:
![image](https://user-images.githubusercontent.com/8977729/53201220-0475ec80-35e9-11e9-9407-7e9c73662e37.png)

If I remove the all of the "/", it looks good, but will not work as expected:
![image](https://user-images.githubusercontent.com/8977729/53201282-2ec7aa00-35e9-11e9-9050-80d626f35e32.png)

**Comment by glennsarti** [comment]
Thanks @thehackadmin .  I've moved it over to the puppet-editor-syntax project as https://github.com/lingua-pupuli/puppet-editor-syntax/issues/27
