### ISSUE TITLE
macOS High Sierra w/PDK :: Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by PTcrusher** [lingua-pupuli/puppet-vscode#500]
### What Versions are you running?

OS Version: macOS High Sierra 10.13.6
VSCode Version: 1.32.3
Puppet Extension Version: 0.18.0
Puppet Agent Version: None
PDK Version (if applicable): 1.10.0

### What You Are Seeing?
`[Info  - 5:23:36 PM] Connection to server got closed. Server will restart.
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require': cannot load such file -- puppet (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
    from /Users/ESO05/.vscode/extensions/jpogran.puppet-vscode-0.18.0/vendor/languageserver/lib/puppet_languageserver.rb:34:in 'require_gems'
    from /Users/ESO05/.vscode/extensions/jpogran.puppet-vscode-0.18.0/vendor/languageserver/lib/puppet_languageserver.rb:165:in 'init_puppet'
    from /Users/ESO05/.vscode/extensions/jpogran.puppet-vscode-0.18.0/vendor/languageserver/puppet-languageserver:10:in '<main>'
[Error - 5:23:36 PM] Connection to server got closed. Server will not be restarted.`

### What is Expected?

Expect puppet to connect to the PDK and show the version in green under the bar.
Intellisense not working as well.

### How Did You Get This To Happen? (Steps to Reproduce)
Fresh system, installed Puppet Extension for VSCODE
Then installed PDK via brew *brew cask install puppetlabs/puppet/pdk*

### Output Log

[error.txt](https://github.com/lingua-pupuli/puppet-vscode/files/3064796/error.txt)

**Comment by PTcrusher** [comment]
sudo gem install puppet --version '5.5.0'

solved the issue

**Comment by glennsarti** [comment]
Hi @PTcrusher thanks for opening and closing this issue.

**Comment by myskov** [comment]
Same problem here (Mojave). The solution helped.  Should this solution be in installation details?

**Comment by glennsarti** [comment]
@myskov Did you change the puppet.installType to 'pdk' ?

It shouldn't be.  The extension should not be using the system ruby.  It should be using the ruby environment that comes from Puppet Agent or PDK. That's why Puppet is missing.

@jpogran We should probably implement  autoswitch between Agent and PDK

**Comment by glennsarti** [comment]
Reopening

**Comment by patatman** [comment]
I also ran into this issue on Mojave.
Only installed the PDK via Brew, and ran into this issue.
As soon as I installed the puppet-agent via Brew, the issue was fixed.
Uninstalling the puppet-agent seems to reproduce the issue again.

**Comment by patatman** [comment]
> I also ran into this issue on Mojave.
> Only installed the PDK via Brew, and ran into this issue.
> As soon as I installed the puppet-agent via Brew, the issue was fixed.
> Uninstalling the puppet-agent seems to reproduce the issue again.

Nevermind, issue is fixed by forcing PDK like suggested.
VScode -> Prefrences -> settings -> Extensions -> Puppet -> Puppet install type
