### ISSUE TITLE
Puppet Litmus integration

### ISSUE THREAD

**Issue by glennsarti** [lingua-pupuli/puppet-vscode#501]
**Summary of the new feature**

From internal Slack

You were soliciting ideas for vscode plugin integrations - one idea in conjunction with litmus is having a inventory.yaml editor with support for structured adding/editing of hosts and using litmus to provision new hosts into that inventory.yaml - might be an interesting experiment if that is useful

**Comment by tphoney** [comment]
so litmus actually takes care of maintaining the inventory file. It adds entries when provisioning a new system. and deletes entries when decommissioning them.

**Comment by jpogran** [comment]
Another suggestion was to add the tasks from https://github.com/puppetlabs/puppetlabs-motd/pull/212. This is likely better placed in pdk templates

**Comment by jpogran** [comment]
Another idea is to implement a [task provider](https://code.visualstudio.com/api/extension-guides/task-provider#task-provider) that will read the rakefile and add litmus specific tasks automatically to the command palate. User specified tasks will win out, but it provides a quick set of default tasks.
