### ISSUE TITLE
Switch default PuppetInstallType to PDK rather than the agent

### ISSUE THREAD

**Issue by albatrossflavour** [lingua-pupuli/puppet-vscode#502]
**Summary of the new feature**

As a user, I would like to be able to install the plugin and use it with the minimum possible steps.  Currently the PuppetInstallType is set to `agent`, which means you have to make a config update to change it to `PDK` unless you have an agent installed on the workstation.

Before PDK, this was pretty common to do, but now I just rely on having PDK there.

I spoke with @jpogran during the office hours session on 02/05/2019 and he suggested I raise a ticket for it.  I've got [a fork](https://github.com/albatrossflavour/puppet-vscode.git) that I'll raise a PR for shortly.

**Comment by jpogran** [comment]
Thanks for the work @albatrossflavour! This is now merged in
