### ISSUE TITLE
libxcrypt-compat required on Fedora 30

### ISSUE THREAD

**Issue by term1n4l** [lingua-pupuli/puppet-vscode#504]
After upgrade to Fedora 30, I was unable to load the puppet language server due to missing libcrypt.so.1. I was able to find this in libxcrypt-compat from the standard repos. Raising issue as an FYI, and so you can add as an extra dependancy for anyone using F30 already (besides me).

**Comment by glennsarti** [comment]
Thanks @term1n4l .  Unfortunately there's nothing we (the extension) authors can do about that as we depend on the packages from Puppet. (PDK and Agent).  It looks like Fedora 30 isn't supported yet so it's not surprising it has an issue.  For now I'm going to close the issue as we can't fix it, but we can re-open once the packages for Fedora 30 are done.
