### ISSUE TITLE
Unable to hide PDK New Module button

### ISSUE THREAD

**Issue by longcao** [lingua-pupuli/puppet-vscode#505]
**As a user, I would like to** be able to hide the "PDK New Module" button on the top right corner of the VS Code window. There doesn't appear to be a setting to hide it, and since it's an infrequently used feature for me I would like to reduce visual noise.

Please let me know if there's already a way to do this!

<img width="164" alt="Screen Shot 2019-05-09 at 11 32 39 AM" src="https://user-images.githubusercontent.com/865236/57481771-c2f3f580-7257-11e9-8dd0-5c3b2986c87d.png">

**Comment by jpogran** [comment]
You are correct, there isn't a setting controlling the visibility of this button. This is a reasonable request, we'll work on it for the next release
