### ISSUE TITLE
Puppet Extensions always adds newline at end of '.epp'

### ISSUE THREAD

**Issue by Musashi178** [lingua-pupuli/puppet-vscode#506]
I am working with VS code and puppet on windows, and when having the puppet-vscode extension installed, a newline will be added to the end of an .epp file on save. I tried to fix this by setting "puppet.format.enable" to false, but it didn't change anything.

### What Versions are you running?

OS Version: Windows 10 Pro 1809
VSCode Version: 1.33.1
Puppet Extension Version: v.0.18.0
Puppet Agent Version: 6.4.2 x64-mingw32
PDK Version (if applicable): 1.10.0.0

### What You Are Seeing?

When saving a file with extension '.epp', a newline is added at the end of file, no matter what

### What is Expected?

The .epp file should not be changed

### How Did You Get This To Happen? (Steps to Reproduce)

1. Create a directory "Test"
2. Create a file named "Test.epp" in it
3. Open in VSCode and enter some text
4. Save the file

=> a newline will be added if the last line is not empty

**Comment by jpogran** [comment]
Hi @Musashi178, the Puppet extension provides the following suggested editor customizations:

```json
      "[puppet]": {
        "editor.tabSize": 2,
        "editor.insertSpaces": true,
        "files.insertFinalNewline": true
      }
```

You can always override any setting in your user configuration by opening the VSCode Preferences and setting the item to the value you want. In this case set `"files.insertFinalNewline"` to `false`. Inserting a final newline is a common practice in Puppet circles, but totally configurable by you.

**Comment by jpogran** [comment]
I'm going to close this out, as this is user configurable
