### ISSUE TITLE
Ideas for a more focused Bolt extension for VS Code. 

### ISSUE THREAD

**Issue by jdub55** [lingua-pupuli/puppet-vscode#514]
**Summary of the new feature**

- A clear and concise description of what Bolt it is and how it can help VSCode users to run commands, deploy code, etc. 
- Intellisense capability to help users with the Bolt syntax
- An easy method of populating a list of comma separated nodes from a file
- Hover over capability for docs and links back to the bolt documentation
- Links to a getting started with Bolt set of files on a github repo. 

---
** As a power developer or sys admin, I would like to be able to try out Bolt for various ad hoc tasks that I need to run on different servers. I would like to be able to use my preferred editor, VSCode to accomplish this.

**Comment by glennsarti** [comment]
Thanks @jdub55 !  This is something we've been considering for a while.

Can I get you clarify some of these points, in particular what you'd like to see vscode doing, for example:

`Inside a Bolt Inventory file I would like to able to have a wizard to help me insert nodes from AWS` 

or

`I would like to be able to run bolt from the command palette: for Bolt Apply current plan`
