### ISSUE TITLE
puppet:// URL without modules/ found

### ISSUE THREAD

**Issue by unixhelden** [lingua-pupuli/puppet-vscode#516]
vscode with actual plugin loaded shows an error with a custom file server resource.

puppet:// URL without modules/ found

The bad thing is, upon saving the manifest the plugin automatically modifies the puppet code which results in file not found errors during run on client.

working code:
 source => "puppet:///jenkins_releases/${service_name}/${service_name}-${service_version}.jar",

after save:
 source => "puppet:///modules/jenkins_releases/${service_name}/${service_name}-${service_version}.jar",

Please leave it alone, k-thx-bye :)

**Comment by jpogran** [comment]
I think you have puppet-lint formatting your document because you have Format on Save enabled, because this is a puppet-lint rule: http://puppet-lint.com/checks/puppet_url_without_modules/.

**Comment by unixhelden** [comment]
I have a puppet lint task, but it has this disabled and is bound to a Keyboard shortcut. 
`
  "version": "2.0.0",
  "tasks": [
    {
      "label": "puppetlint",
      "type": "shell",
      "command": "puppet-lint",
      "args": [
        "--no-puppet_url_without_modules-check",
        "-f",
        "${file}"
      ]
    }
  ]
}`

But after deactivating the following config option of the puppet plugin i don't see the error and also dont get a modified file with saving i also do not get the warning. 

Puppet>Format:Enable  
![Screenshot](https://user-images.githubusercontent.com/6481580/58361939-4cc7d380-7e92-11e9-8e69-1813944d5b49.png)

**Comment by unixhelden** [comment]
Ok, i still get the Error in the Problems Window, but no one edits the code.

![Screenshot2](https://user-images.githubusercontent.com/6481580/58361998-d4addd80-7e92-11e9-8712-75652a2a04aa.png)

**Comment by unixhelden** [comment]
Oh boy, its too late and now i get what you wrote :( Sorry for the noise.

I'll try to add this to my ~/.puppet-lint.rc
