### ISSUE TITLE
Plugin freezes when using a multi-resource declaration

### ISSUE THREAD

**Issue by wilrodriguez** [lingua-pupuli/puppet-vscode#525]
### What Versions are you running?

OS Version: OSX 10.14.5
VSCode Version: 1.34.0
Puppet Extension Version: 0.18.0
Puppet Agent Version: 6.4.0
PDK Version (if applicable): 1.10.0

### What You Are Seeing?

I've noticed that when I try to manage a multi-resource declaration, say something like this one that I stole from #464 the language server will freeze.

```puppet
file {
  default:
    ensure => file,
    mode   => '0644',
    notify => Haproxy::Service['haproxy'],
  ;
  $haproxy_cert_dir:
    ensure => directory,
    mode   => '0755',
  ;
  $puppet_ca_file:
    source => '/etc/puppetlabs/puppet/ssl/certs/ca.pem',
  ;
  $puppet_crl_file:
    source => '/etc/puppetlabs/puppet/ssl/crl.pem',
  ;
}
```

When it freezes, it doesn't matter if you reload, or even restart the whole editor, it will never load. I've got a number of users who report similar behavior, but we never could figure out what was causing it until now. It's worth noting that the first resource body after the default will work, though it'll throw duplicate parameter errors if you redefine any parameters to override the default. The moment you add the second resource body, however, it'll immediately freeze the language server and the language server will stay unresponsive until the code is deleted/file closed *and* the window has been reloaded.

### What is Expected?

It would be cool if it didn't freeze.

### How Did You Get This To Happen? (Steps to Reproduce)

Add a multi-body resource to your manifest.

### Output Log

Can't upload logs due to company DLP scanners, I can provide them via our support box share though, just tell me where to put them.

**Comment by jpogran** [comment]
HI @wilrodriguez , thanks for contacting us.

Are you using the PDK or Puppet Agent as the source for the extension? Did you modify the installs to add additional gems or more ruby versions, or are these default installations? We've had some users report problems when they were using customized installs that had bad gem installs or environmental paths.

I see you're on 0.18.0 of the extension, we just released [0.18.1](https://github.com/lingua-pupuli/puppet-vscode/blob/master/CHANGELOG.md#0181---2019-06-07) which fixed #436, which sounds similar to your problem. Do you mind updating and checking if that resolved your issue?

**Comment by wilrodriguez** [comment]
I didn't see your update until just now. But, sure enough, it does look like 0.18.1 might have fixed this issue for me. I'm going to go ahead and close the issue, I'll reopen it if it happens again though.

**Comment by glennsarti** [comment]
Thanks @wilrodriguez
