### ISSUE TITLE
ZFS library initialization failed

### ISSUE THREAD

**Issue by term1n4l** [lingua-pupuli/puppet-vscode#559]
### What Versions are you running?

OS Version: Fedora 30
VSCode Version: 1.37.1
Puppet Extension Version: 0.20.0
PDK Version: 1.13.0

### What You Are Seeing?
In the output pane for the puppet extension I am currently receiving:

'connect: Permission denied'
'internal error: failed to initialize ZFS library'

I initially also had an error stating that I needed to start and enable the zfs-fuse service.

### What is Expected?
None of these errors. I'm not using ZFS on my system.

### How Did You Get This To Happen? (Steps to Reproduce)

Loaded the Extension. I am using Puppet version 5.5.16 instead of the default option.

### Output Log
DEBUG: 2019-09-04T02:36:53.237Z Registered extension.pdkNewModule command
DEBUG: 2019-09-04T02:36:53.237Z Registered extension.pdkNewClass command
DEBUG: 2019-09-04T02:36:53.237Z Registered extension.pdkNewTask command
DEBUG: 2019-09-04T02:36:53.237Z Registered extension.pdkValidate command
DEBUG: 2019-09-04T02:36:53.237Z Registered extension.pdkTestUnit command
DEBUG: 2019-09-04T02:36:53.237Z Found a valid Puppet installation at /opt/puppetlabs/pdk/puppet
DEBUG: 2019-09-04T02:36:53.237Z Setting status bar to Initializing
DEBUG: 2019-09-04T02:36:53.237Z Configuring language client options
DEBUG: 2019-09-04T02:36:53.237Z Creating server options
DEBUG: 2019-09-04T02:36:53.237Z [getRubyEnvFromPDK] Using environment variable DEVKIT_BASEDIR=/opt/puppetlabs/pdk
DEBUG: 2019-09-04T02:36:53.237Z [getRubyEnvFromPDK] Using environment variable GEM_HOME=/opt/puppetlabs/pdk/share/cache/ruby/2.4.0
DEBUG: 2019-09-04T02:36:53.237Z [getRubyEnvFromPDK] Using environment variable GEM_PATH=/opt/puppetlabs/pdk/private/ruby/2.4.5/lib/ruby/gems/2.4.0:/opt/puppetlabs/pdk/share/cache/ruby/2.4.0:/opt/puppetlabs/pdk/private/puppet/ruby/2.4.0
DEBUG: 2019-09-04T02:36:53.237Z [getRubyEnvFromPDK] Using environment variable RUBY_DIR=/opt/puppetlabs/pdk/private/ruby/2.4.5
DEBUG: 2019-09-04T02:36:53.237Z [getRubyEnvFromPDK] Using environment variable RUBYLIB=/opt/puppetlabs/pdk/lib:
DEBUG: 2019-09-04T02:36:53.237Z [getRubyEnvFromPDK] Using environment variable PATH=/opt/puppetlabs/pdk/bin:/opt/puppetlabs/pdk/private/ruby/2.4.5/bin:/home/<username>/.local/bin:/home/<username>/bin:/usr/lib64/qt-3.3/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
DEBUG: 2019-09-04T02:36:53.237Z [getRubyEnvFromPDK] Using environment variable RUBYOPT=rubygems
DEBUG: 2019-09-04T02:36:53.237Z [getRubyEnvFromPDK] Editor Services will invoke with: /opt/puppetlabs/pdk/private/ruby/2.4.5/bin/ruby /home/<username>/.vscode/extensions/jpogran.puppet-vscode-0.20.0/vendor/languageserver/puppet-languageserver --stdio --timeout=10 --local-workspace=/home/<username>/Source/control-repo --puppet-version=5.5.16 --debug=/home/<username>/.vscode/extensions/jpogran.puppet-vscode-0.20.0/debug.log
DEBUG: 2019-09-04T02:36:53.237Z Creating language client
DEBUG: 2019-09-04T02:36:53.239Z Setting status bar to Initialization Complete
DEBUG: 2019-09-04T02:36:53.239Z Configuring Local::stdio connection handler
DEBUG: 2019-09-04T02:36:53.239Z Setting status bar to Starting languageserver
DEBUG: 2019-09-04T02:36:53.240Z Registered Format Document provider
DEBUG: 2019-09-04T02:36:53.240Z Registered extension.puppetShowNodeGraphToSide command
DEBUG: 2019-09-04T02:36:53.240Z Registered onDidSaveTextDocument for node graph event handler
DEBUG: 2019-09-04T02:36:53.240Z Registered DebugAdapterDescriptorFactory for Puppet
DEBUG: 2019-09-04T02:36:53.240Z Registered DebugConfigurationProvider for Puppet
DEBUG: 2019-09-04T02:36:53.802Z pdk shell started, pid: 12712
DEBUG: 2019-09-04T02:36:54.361Z Setting status bar to Loading Puppet
connect: Permission denied
internal error: failed to initialize ZFS library
DEBUG: 2019-09-04T02:36:55.376Z Setting status bar to 5.5.16
DEBUG: 2019-09-04T02:36:56.364Z Setting status bar to 5.5.16

**Comment by jpogran** [comment]
Hi @term1n4l , thanks for the report. I can confirm nothing in the extension itself uses ZFS, so I'm not sure where it's coming from.

I noticed those messages don't have the Puppet Extension formatting `DEBUG: ${date} ${message}`, which means to me it's not the extension writing those lines. You're using STDIO protocol, so I wonder if it's coming from STDIN in from something else in your profile?

We have other users who use Fedora who haven't reported something similar. Is there something else on your machine that would use ZFS if its there?
