### ISSUE TITLE
puppet open node error

### ISSUE THREAD

**Issue by jrbast** [lingua-pupuli/puppet-vscode#578]
### What Versions are you running?

OS Version: Oracle Linux VM
VSCode Version: 1.39.2
Puppet Extension Version: 0.21.0
PDK Version: 1.14.1

### What You Are Seeing?
There were no resources created in the node graph. Is there an include statement missing?

![image](https://user-images.githubusercontent.com/27219477/68405469-c3594480-0145-11ea-9917-e0e5cb0bbf9b.png)

### What is Expected?
Node graph like your examples show

### How Did You Get This To Happen? (Steps to Reproduce)
In command pallet, entered puppet open node

### Output Log

For information how to capture verbose logs, look [here](https://github.com/lingua-pupuli/puppet-vscode#2-capture-verbose-logs-and-send-them-to-us)
-->

**Comment by jpogran** [comment]
Thanks for the screenshot and explanation. In order for the graph to be generated from a class, there has to be an `include name_of_class` inside the open file. In your example, there has to be a `include hpsu_apps_common::spa::users` as well as your class declaration.

**Comment by jrbast** [comment]
Ok, so I will use a role file with includes...
![with_includes](https://user-images.githubusercontent.com/27219477/68406806-13390b00-0148-11ea-93ed-a29645484ef0.PNG)

**Comment by jpogran** [comment]
I meant that if you have a file like this:

```
class hpsu_apps_common::spa::users {
}
```

You add an `include` line after the class so Puppet pulls in the reference

```
class hpsu_apps_common::spa::users {
}

include hpsu_apps_common::spa::users
```

**Comment by jrbast** [comment]
Well that makes no sense?   include inside the class...
That does not work either, same error as above

**Comment by glennsarti** [comment]
Ahh I see, this is in a Control Repo. 

@jpogran is right in the include statement, however, control repos aren't fully understood by Puppet Editor Services (PES) yet! For example, control repos can have custom module paths which PES doesn't search.

It is on the roadmap to add control repo support to Node Graph using utilities like Onceover and R10K.
