### ISSUE TITLE
[Feature] Automate updating PES and import the changelog

### ISSUE THREAD

**Issue by genebean** [lingua-pupuli/puppet-vscode#601]
**Summary of the new feature**

![image](https://user-images.githubusercontent.com/966789/71520498-77479800-288a-11ea-805d-75c430d29861.png)

The image above tells me from inside VS Code that `puppet-editor-services` was upgraded in this release but does not tell me what bugs that are seen while using the extension are fixed as a result. As a user, I would like to know from reading the changelog in VS Code that things like https://github.com/lingua-pupuli/puppet-editor-services/issues/201 have been fixed and, in general, think I should be able to basically see all the things from https://github.com/lingua-pupuli/puppet-editor-services/milestone/16?closed=1 in this release's Added/Changed/Fixed/Removed sections.

**Comment by glennsarti** [comment]
Hi @genebean .  We already do populate this Changelog from the Puppet-Editor-Services (PES) changelog  e.g. https://github.com/lingua-pupuli/puppet-editor-services/blob/master/CHANGELOG.md#0230---2019-12-04 has 6 items, and in the image above there are 6 items pertaining to the PES 0.23.0

However this is a manual process.  And you're right, PES issue 201 was missed from the changelog. as is PES Issue 139.  We can't directly add all things in the milestone, as the milestone includes Issues and Pull Requests, whereas the changelog typically only includes Pull Requests.

![image](https://user-images.githubusercontent.com/5819622/71537528-5cdbf000-2958-11ea-80f6-74d7445f4824.png)

**Comment by glennsarti** [comment]
For the moment, I'm going to change the title of this request to "Automate updating PES and import the changelog"

I've created https://github.com/lingua-pupuli/puppet-editor-services/issues/212 to track the changelog verification.

**Comment by genebean** [comment]
I totally missed the ones you point out but they are plain as day now that I know what I’m looking for 😀 

Are you all using any tooling to help generate the changelog entries?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by glennsarti** [comment]
> Are you all using any tooling to help generate the changelog entries?

Nope. The investment in time hasn't been worth it so far.

**Comment by genebean** [comment]
Wasn’t sure if the same tool we use in the PDK would generate it for you (or at lease do most of the work). 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by glennsarti** [comment]
That particular ruby gem has a very bad experience for Windows users.  And this project is Node. I estimate it'd take at least a year before we'd get a return-on-investment of time. And even if we get wrong manually, only take a minute to fix. 🤷‍♂️

**Comment by jpogran** [comment]
Closing this, as we don't have the ticket volume or number of projects to justify this at this time. Thanks for the suggestion!
